eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@service-discovery:8080/eureka/

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/book?serverTimezone=Asia/Shanghai # 修改:3306前的mysql为localhost可本地测试
    username: gaussdb
    password: ${DB_PASSWORD:password}
